### ISSUE TITLE
Use stream-based logging functions

### ISSUE THREAD

**Issue by dogoepp** [resibots/hexa_control#2]
Instead of using ROS_LOGLEVEL(), use ROS_LOGLEVEL_STREAM, where LOGLEVEL is one of DEBUG, ERROR, INFO, etc.

Unless there is a good reason not to.

**Comment by costashatz** [comment]
No there have exactly the same functionality: the simple one is like a `printf` and stream version is like a `cout`. I will change them.

**Comment by costashatz** [comment]
Fixed in 2aa4909! Check and close!

**Comment by dogoepp** [comment]
Thanks !
